import { nanoid } from "nanoid"
export const bookData = [
    {
        id:nanoid(),
        img:'/assets/image2.jpg',
        title:'Red Silk Saree',
        type:'science',
        description:'Silk sarees are more than just an attire; they are a cherished heritage passed down through generations and a symbol of elegance and tradition in India. This guide explores the different types of silk sarees, each with its unique weave, design, and regional identity.',
        rating:'4.5',
    },
    {
        id:nanoid(),
        img:'/assets/image3.jpg',
        title:'Designer Saree',
        type:'fiction',
        description:'A designer saree is more than just a piece of cloth; it is a work of art that blends traditional craftsmanship with contemporary design sensibilities.',
        rating:'4.5',
    },{
        id:nanoid(),
        img:'/assets/image4.jpg',
        title:'Straight Cut Kurti',
        type:'non_fiction',
        description:'A Kurti is a traditional Indian attire, popular among women of all ages. It is a shorter version of the Kurta.',
        rating:'4.5',
    },{
        id:nanoid(),
        img:'/assets/image5.jpg',
        title:'Jeans',
        type:'fantacy',
        description:'Jeans are a type of trousers made from denim or dungaree cloth.',
        rating:'2.5',
    },{
        id:nanoid(),
        img:'/assets/image6.jpg',
        title:'Yellow Silk Saree',
        type:'science',
        description:'Silk sarees are more than just an attire; they are a cherished heritage passed down through generations and a symbol of elegance and tradition in India. This guide explores the different types of silk sarees, each with its unique weave, design, and regional identity.',
        rating:'4.2',
    },
    {
        id:nanoid(),
        img:'/assets/image7.jpg',
        title:'Unstitched Material',
        type:'crime',
        description:'Unlike a pre-made suit, where the garment is already assembled, unstitched fabric allows you to work with a tailor or seamstress to design and construct a suit that fits your unique body shape and personal style.',
        rating:'4.2',
    },
    {
        id:nanoid(),
        img:'/assets/image8.jpg',
        title:'Georgette Saree',
        type:'fiction',
        description:'A designer saree is more than just a piece of cloth; it is a work of art that blends traditional craftsmanship with contemporary design sensibilities.',
        rating:'4.1',
    },{
        id:nanoid(),
        img:'/assets/image9.jpg',
        title:'Unstitched Material',
        type:'crime',
        description:'Unlike a pre-made suit, where the garment is already assembled, unstitched fabric allows you to work with a tailor or seamstress to design and construct a suit that fits your unique body shape and personal style.',
        rating:'4.0',
    },{
        id:nanoid(),
        img:'/assets/image10.jpg',
        title:'Pencil-fit Jean',
        author:'Yuval Noah Harari',
        type:'fantacy',
        description:'Jeans are a type of trousers made from denim or dungaree cloth.',
        rating:'4.8',
    },{
        id:nanoid(),
        img:'/assets/image11.jpg',
        title:'Green Silk Saree',
        type:'science',
        description:'Silk sarees are more than just an attire; they are a cherished heritage passed down through generations and a symbol of elegance and tradition in India. This guide explores the different types of silk sarees, each with its unique weave, design, and regional identity.',
        rating:'4.3',
    },
    {
        id:nanoid(),
        img:'/assets/image12.jpg',
        title:'Unstiched Material',
        type:'crime',
        description:'Unlike a pre-made suit, where the garment is already assembled, unstitched fabric allows you to work with a tailor or seamstress to design and construct a suit that fits your unique body shape and personal style.',
        rating:'4.3',
    },
    {
        id:nanoid(),
        img:'/assets/image13.jpg',
        title:'Anarkali Kurti',
        type:'non_fiction',
        description:'A Kurti is a traditional Indian attire, popular among women of all ages. It is a shorter version of the Kurta.',
        rating:'4.3',
    }
]